name: Deploy Safe Spotter

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      env:
        CI: false
    
    - name: Test
      run: echo "Add tests in the future"
      
    - name: Check format
      run: echo "Add prettier/eslint checks in the future"